name: Test pipeline CI/CD
run-name: ${{ github.actor }} is trigger run GitHub Actions 🚀
on:
  release:
    types: [published]
  push:
    branches:
      - "main"
    tags:
      - "v*"
env:
  APP_STAGE: ${{ github.ref_name == 'main' && 'stag' || 'prod' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Information
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.event.action }}
          echo ${{ env.APP_STAGE }}
