name: Test pipeline CI/CD
run-name: ${{ github.actor }} is trigger run GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Information
        run: |
          echo "The commit SHA is: $GITHUB_SHA"
          echo "The run id is: $GITHUB_RUN_ID" 
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"